name: Fetch Stock on Hand MTD

on:
  workflow_dispatch:      # Allows trigger via API dispatch and manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pandas numpy requests PyJWT gspread google-auth google-api-python-client pytz

      - name: Run Stock on Hand MTD Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "Running Fetch Inventory Activity MTD script..."
          python fetch_inventory_activity_mtd.py
