name: Hourly Order Flow Alert

on:

  workflow_dispatch:

jobs:

  order-flow-alert:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests PyJWT

      - name: Run hourly order flow
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          RISTA_API_BASE: ${{ secrets.RISTA_API_BASE }}
        
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}

        run: |
          echo "Running script..."
          python order_flow_hourly_alert.py
